#!/usr/bin/env python

##########################################################################
# Copyright 2009 Broadcom Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# File: git-jira-hook
# Author: Joyjit Nath
#
###########################################################################

# Purpose:
# This is a git hook, to be used in an environment where git is used
# as the source control and Jira is used for bug tracking.
#
# See accompanying README file for help in using this.
#


import logging
import sys
import os
import requests 
import subprocess
import re
import getpass
import stat
import ConfigParser
import string
from suds.client import Client

loglevel=logging.INFO
#loglevel=logging.DEBUG

myname = os.path.basename(sys.argv[0])
global_jirarc = os.path.dirname(sys.argv[0]) + "/../jirarc"
if len(sys.argv) > 1 and sys.argv[1].startswith('--action='):
    action_arg = sys.argv.pop(1)
    myname = action_arg.split('=')[1]

logging.basicConfig(level=loglevel, format="%(levelname)s %(name)s %(message)s")
logging.getLogger('suds').setLevel(logging.INFO)
if loglevel != logging.DEBUG:
    # suds prints out a lot of ERRORs that we don't need to see, since it raises an Exception also
    logging.getLogger('suds.client').setLevel(logging.CRITICAL)
log = logging.getLogger(myname)

def main():
    if myname == "pre-receive":
        return handle_pre_receive()
    else:
        log.error("invoked as '%s'. Need to be invoked as pre-receive. " , myname)
        return -1


# Performs the git "pre_receive" hook
# This hook is triggered on the remote repo, as a result
# of "git push"
def handle_pre_receive():
    buf = sys.stdin.read()
    log.debug("handle_post_receive: stdin='%s'", buf)
    if len(string.split(buf, ' ')) != 3:
	log.info("Unexpected receive message, probably tag push, not handling")
        return 0;

    (old_commit_id, new_commit_id, ref) =  string.split(buf, ' ')

    if old_commit_id == None or new_commit_id == None or ref == None:
        log.error("post-receive hook stdin is incorrect '%s'", buf)
        return -1

    branch = git_get_branchname_from_ref(ref)
    if not enabled_on_branch(branch):
        return 0

    jira_url = get_jira_url()
    if jira_url == None:
        return -1

    jira_auth = jira_login(jira_url)
    if jira_auth == None:
        return -1

    zeros = '0000000000000000000000000000000000000000'
    if new_commit_id == zeros:
        log.debug('branch at %s deleted' % old_commit_id)
        return 0
   
    if old_commit_id == zeros:
        log.debug('new branch at %s' % new_commit_id)
        commit_id_array = [new_commit_id]
    else:
        commit_id_array = git_get_array_of_commit_ids(old_commit_id, new_commit_id)

    if commit_id_array == None or len(commit_id_array)==0:
        log.error("no commit ids!")
        return -1

    for commit_id in commit_id_array:
        commit_text = branch + ': ' +  git_get_commit_text(commit_id)
	commit_title = git_get_commit_title(commit_id)
        jira_add_comment(jira_auth, commit_id, commit_text, commit_title, branch)
        
    return 0


def jira_add_comment(jira_auth, commit_id, commit_text, commit_title, branch):
    gitweb_url = get_gitweb_url()
    gitweb_branch_url = get_gitweb_branch_url()

    if gitweb_url != None or gitweb_url != "":
        link = gitweb_url + commit_id

    call_pattern_hook(commit_text, commit_title, '', jira_add_comment_to_issue, jira_auth, link)
    #TODO transitions
    return



# Given a function pointer, iterates through the commit message
# text for Jira magic words, and calls the function repeatedly
# returns number of issues found and touched
# in case of error, return -1
def call_pattern_hook(text, title, pattern, hookfn, jira_auth, link):
    if not callable(hookfn):
        log.error("Hook function is not callable");
        exit(-1)

    magic = re.compile(pattern + '(\w\w*-\d\d*)')

    iterator = magic.finditer(text)
    issue_count = 0
    seen_issues = set()
    for match in iterator:
        issuekey = match.group(1)
        if issuekey in seen_issues:
            continue
        else:
            seen_issues.add(issuekey)
	log.debug("Calling " +  hookfn.__name__ + " for " + issuekey)

        ret = hookfn(issuekey, jira_auth, text, title, link)
        if ret != 0:
            return -1
        else:
            issue_count += 1

    return issue_count

#-----------------------------------------------------------------------------
# Jira helper functions
#

def jira_login(jira_url):

    auth = {}
    auth["username"] = get_cfg_value(global_jirarc, jira_url, "username")
    auth["password"] = get_cfg_value(global_jirarc, jira_url, "password")

    return auth

def jira_add_comment_to_issue(issuekey, jira_auth, text, title, link):
    try:
	headers = {
    		'Content-type': 'application/json',
	}
	data = '{"relationship":"Related commits","object":{"url":"' + link + '","title":"' + title + '","summary":""}}'
	r = requests.post( get_jira_url() +'/rest/api/latest/issue/' + issuekey + '/remotelink', headers=headers, data=data, auth=(jira_auth["username"], jira_auth["password"]))
        log.debug("Request: %s", r.json)
	return 0

    except Exception, e:
        log.error("Error adding comment to issue '%s' in Jira", issuekey)
        log.debug(e)
        return -1


def jira_add_comment_to_and_progress_issue(issuekey, jira_soap_client, jira_auth, jira_text):
    try:
        jira_soap_client.service.progressWorkflowAction(jira_auth, issuekey, '4', [])
        log.debug("Start progress issue '%s' in Jira", issuekey)
        return 0

    except Exception, e:
        log.error("Error start progressing issue '%s' in Jira", issuekey)
        log.debug(e)
        return -1


def jira_add_comment_to_and_resolve_issue(issuekey, jira_soap_client, jira_auth, jira_text):
    try:
        jira_soap_client.service.progressWorkflowAction(jira_auth, issuekey, '5', [])
        log.debug("Resolve issue '%s' in Jira", issuekey)
        return 0

    except Exception, e:
        log.error("Error resolving issue '%s' in Jira", issuekey)
        log.debug(e)
        return -1


def jira_add_comment_to_and_reopen_issue(issuekey, jira_soap_client, jira_auth, jira_text):
    try:
        jira_soap_client.service.progressWorkflowAction(jira_auth, issuekey, '3', [])
        log.debug("Reopen issue '%s' in Jira", issuekey)
        return 0

    except Exception, e:
        log.error("Error reopening issue '%s' in Jira", issuekey)
        log.debug(e)
        return -1



def jira_add_comment_to_and_close_issue(issuekey, jira_soap_client, jira_auth, jira_text):
    try:
        jira_soap_client.service.progressWorkflowAction(jira_auth, issuekey, '2', [])
        log.debug("Close issue '%s' in Jira", issuekey)
        return 0

    except Exception, e:
        log.error("Error closing issue '%s' in Jira", issuekey)
        log.debug(e)
        return -1


#-----------------------------------------------------------------------------
# Miscellaneous Jira related utility functions
#
def get_jira_url():
    jira_url = git_config_get("jira.url")
    if jira_url == None or jira_url == "":
        log.error("Jira URL is not set. Please use 'git config jira.url <actual-jira-url> to set it'")
        return None

    return jira_url

#---------------------------------------------------------------------
# Misc. helper functions
#

def get_gitweb_url():
    value = git_config_get("gitweb.url")
    value = value.replace("%PROJECTNAME%", os.path.abspath(sys.argv[0]+"/../../").replace(git_config_get("gitweb.root")+"/",""))
    log.debug("Gitweb URL = " + value)
    return value

def get_gitweb_branch_url():
    value =  git_config_get("gitweb.branchurl")
    value = value.replace("%PROJECTNAME%", os.path.abspath(sys.argv[0]+"/../../").replace(git_config_get("gitweb.root")+"/",""))
    log.debug("Gitweb URL = " + value)
    return value

def get_cfg_value(cfg_file_name, section, key, silent=False):
    try:
        cfg = ConfigParser.ConfigParser()
        cfg.read(cfg_file_name)
        value = cfg.get(section, key)
    except:
        if not silent:
            log.warn("Error reading %s looking for [%s] %s" % (cfg_file_name, section, key), exc_info=True)
        return None
    return value


def save_cfg_value(cfg_file_name, section, key, value):
    try:
        cfg = ConfigParser.SafeConfigParser()
    except Exception, e:
        log.warning("Failed to instantiate a ConfigParser object")
        log.debug(e)
        return None

    try:
        cfg.read(cfg_file_name)
    except Exception, e:
        log.warning("Failed to read " + cfg_file_name)
        log.debug(e)
        return None

    try:
        cfg.add_section(section)
    except ConfigParser.DuplicateSectionError,e:
        log.debug("Section '%s' already exists in '%s'", section, cfg_file_name)

    try:
        cfg.set(section, key, value)
    except Exception,e:
        log.warning("Failed to add '%s' to '%s'", key, cfg_file_name)
        log.debug(e)

    try:
        cfg.write(open(cfg_file_name, 'wb'))
    except Exception, e:
        log.warning("Failed to write '%s'='%s' to file %s", key, value, cfg_file_name)
        log.debug(e)
        return None
    return 1

# given a string, executes it as an executable, and returns the STDOUT
# as a string
def get_shell_cmd_output(cmd):
    try:
        proc = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
        return proc.stdout.read().rstrip('\n')
    except KeyboardInterrupt:
        log.info("... interrupted")

    except Exception, e:
        log.error("Failed trying to execute '%s'", cmd)

#----------------------------------------------------------------------------
# git helper functions
#

# Read git config of "git-jira-hook.branches"
# Parse out the comma (and space) separated list of
# branch names.
# Then compare against current branchname to see
# if we need to be enabled.
# Return False if we should not be enabled
def enabled_on_branch(current_branchname):
    log.debug("Test if '%s' is enabled...", current_branchname)
    if current_branchname is None:
        # e.g. a tag
        return False
    branchstr = git_config_get("git-jira-hook.branches")
    if branchstr == None or string.strip(branchstr) == "":
        log.debug("All branches enabled")
        return not False

    branchlist = string.split(branchstr, ',')

    for branch in branchlist:
        branch = string.strip(branch)
        if current_branchname == branch:
            log.debug("Current branch '%s' is enabled", current_branchname)
            return not False

    log.debug("Curent branch '%s' is NOT enabled", current_branchname)
    return False

# Get our current branchname
def git_get_curr_branchname():
    buf = get_shell_cmd_output("git branch --no-color")
    # buf is a multiline output, each line containing a branch name
    # the line that starts with a "*" contains the current branch name

    m = re.search("^\* .*$", buf, re.MULTILINE)
    if m == None:
        return None

    return buf[m.start()+2 : m.end()]


# Given a "ref" string (such as while doing a push
# to a remote repo), parse out the branch name
def git_get_branchname_from_ref(ref):
    # "refs/heads/<branchname>"
    if ref.startswith("refs/tags/"):
        return None
    elif not ref.startswith("refs/heads/"):
        log.error("Invalid ref '%s'", ref)
        exit(-1)

    return string.strip(ref[len("refs/heads/"):])


def git_config_get(name):
    return get_shell_cmd_output("git config '" + name + "'")

def git_config_set(name, value):
    os.system("git config " + name + " '" + value + "'")

def git_config_unset(name):
    os.system("git config --unset-all " + name)

def git_get_commit_text(commit_id):
    return get_shell_cmd_output("git rev-list --pretty --max-count=1 " + commit_id)

def git_get_commit_title(commit_id):
    return get_shell_cmd_output("git show -s --date=short --pretty=format:'%h - %an, %ad: %s'  " + commit_id)

def git_get_last_commit_id():
    return get_shell_cmd_output("git log --pretty=format:%H -1")

def git_get_array_of_commit_ids(start_id, end_id):
    output = get_shell_cmd_output("git rev-list --reverse " + start_id + ".." + end_id)
    if output == "":
        return None

    # parse the result into an array of strings
    commit_id_array = string.split(output, '\n')
    return commit_id_array

def git_get_branches_with_commit(commit_id):
    output = get_shell_cmd_output("git branch --contains %s" % commit_id)
    return [b.replace('* ', '').strip() for b in output.split('\n')]

#----------------------------------------------------------------------------
# python script entry point. Dispatches main()
if __name__ == "__main__":
  sys.exit (main())
